/**
 * Manual `Env` augmentation for secret-only bindings.
 *
 * `bff/worker-configuration.d.ts` is fully generated by
 * `wrangler types -c bff/wrangler.jsonc` and covers everything declared in
 * `bff/wrangler.jsonc` (`vars`, `services`). Secrets deliberately do NOT
 * appear in `wrangler.jsonc` (that file is committed; secrets are provided
 * via `wrangler secret put -c bff/wrangler.jsonc` in production and
 * `bff/.dev.vars` locally), so `wrangler types` has no way to know about
 * them. This file merges the remaining secret-only members onto the same
 * global `Env` interface. It is NOT regenerated by `wrangler types` and MUST
 * be kept in sync by hand whenever a secret-only binding is added or
 * removed.
 */
interface Env {
  /** Shared dashboard credential, compared via `verifyTokens` in `POST /auth/session`. */
  DASHBOARD_SECRET: string;
  /** HMAC signing key for the session cookie issued after a successful `DASHBOARD_SECRET` check. */
  DASHBOARD_SESSION_KEY: string;
  /** Shared MCP bearer token, injected only on the `SEO_MCP` service-binding fetch. */
  MCP_AUTH_TOKEN: string;
}
